// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_Manager_Beta.Data;

#nullable disable

namespace Task_Manager_Beta.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_Manager_Beta.Data.Assignment", b =>
                {
                    b.Property<int>("Iduser")
                        .HasColumnType("int")
                        .HasColumnName("IDUser");

                    b.Property<int>("Idtask")
                        .HasColumnType("int")
                        .HasColumnName("IDTask");

                    b.Property<int>("Idassignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDAssignment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idassignment"));

                    b.HasKey("Iduser", "Idtask")
                        .HasName("PK__ASSIGNME__612AE3C007018D2B");

                    b.HasIndex("Idtask");

                    b.ToTable("ASSIGNMENT", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Condition", b =>
                {
                    b.Property<int>("Idcondition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCondition");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcondition"));

                    b.Property<int>("Idpermission")
                        .HasColumnType("int")
                        .HasColumnName("IDPermission");

                    b.Property<int>("Idworkflow")
                        .HasColumnType("int")
                        .HasColumnName("IDWorkflow");

                    b.HasKey("Idcondition")
                        .HasName("PK__CONDITIO__452B4D93615D6001");

                    b.HasIndex("Idpermission");

                    b.HasIndex("Idworkflow");

                    b.ToTable("CONDITION", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Listtemplate", b =>
                {
                    b.Property<int>("IdlistTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDListTemplate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdlistTemplate"));

                    b.Property<int>("Idtemplate")
                        .HasColumnType("int")
                        .HasColumnName("IDTemplate");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdlistTemplate")
                        .HasName("PK__LISTTEMP__55547DE54957B17C");

                    b.HasIndex("Idtemplate");

                    b.ToTable("LISTTEMPLATE", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Member", b =>
                {
                    b.Property<int>("Idmember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMember");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idmember"));

                    b.Property<int>("Idproject")
                        .HasColumnType("int")
                        .HasColumnName("IDProject");

                    b.Property<int>("Iduser")
                        .HasColumnType("int")
                        .HasColumnName("IDUser");

                    b.HasKey("Idmember")
                        .HasName("PK__MEMBER__7EB75A63B9ADC7C1");

                    b.HasIndex("Idproject");

                    b.HasIndex("Iduser");

                    b.ToTable("MEMBER", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Permisssion", b =>
                {
                    b.Property<int>("Idpermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPermission");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpermission"));

                    b.Property<int>("Idproject")
                        .HasColumnType("int")
                        .HasColumnName("IDProject");

                    b.Property<int>("Iduser")
                        .HasColumnType("int")
                        .HasColumnName("IDUser");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Privilege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idpermission")
                        .HasName("PK__PERMISSS__0553C49A071A4B4F");

                    b.HasIndex("Idproject");

                    b.HasIndex("Iduser");

                    b.ToTable("PERMISSSION", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Project", b =>
                {
                    b.Property<int>("Idproject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProject");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproject"));

                    b.Property<DateTime?>("DayCreate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Hide")
                        .HasColumnType("int");

                    b.Property<int?>("Idleader")
                        .HasColumnType("int")
                        .HasColumnName("IDLeader");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idproject")
                        .HasName("PK__PROJECT__B0529955FD19BFEF");

                    b.ToTable("PROJECT", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Status", b =>
                {
                    b.Property<int>("Idstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDStatus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idstatus"));

                    b.Property<int>("Idproject")
                        .HasColumnType("int")
                        .HasColumnName("IDProject");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idstatus")
                        .HasName("PK__STATUS__8DA24510AF0F9F38");

                    b.HasIndex("Idproject");

                    b.ToTable("STATUS", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Task", b =>
                {
                    b.Property<int>("Idtask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTask");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtask"));

                    b.Property<DateTime?>("DayCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DayStart")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<int?>("Hide")
                        .HasColumnType("int");

                    b.Property<int>("Idproject")
                        .HasColumnType("int")
                        .HasColumnName("IDProject");

                    b.Property<int>("Idstatus")
                        .HasColumnType("int")
                        .HasColumnName("IDStatus");

                    b.Property<string>("TaskName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idtask")
                        .HasName("PK__TASK__BCC3A1F9504858B2");

                    b.HasIndex("Idproject");

                    b.HasIndex("Idstatus");

                    b.ToTable("TASK", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Taskdetail", b =>
                {
                    b.Property<int>("Idtask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTask");

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idtask")
                        .HasName("PK__TASKDETA__BCC3A1F9E297B0EB");

                    b.ToTable("TASKDETAILS", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Template", b =>
                {
                    b.Property<int>("Idtemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTemplate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtemplate"));

                    b.Property<string>("TemplateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idtemplate")
                        .HasName("PK__TEMPLATE__AB4388EFB0D1E74B");

                    b.HasIndex(new[] { "TemplateName" }, "UQ__TEMPLATE__A6C2DA6656661883")
                        .IsUnique()
                        .HasFilter("[TemplateName] IS NOT NULL");

                    b.ToTable("TEMPLATE", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.User", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iduser"));

                    b.Property<string>("Avatar")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Iduser")
                        .HasName("PK__USER__EAE6D9DFA1CC6D4F");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Workflow", b =>
                {
                    b.Property<int>("Idworkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDWorkflow");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idworkflow"));

                    b.Property<int>("Idstatus")
                        .HasColumnType("int")
                        .HasColumnName("IDStatus");

                    b.Property<string>("Transition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idworkflow")
                        .HasName("PK__WORKFLOW__7D45E40A469AE309");

                    b.HasIndex("Idstatus");

                    b.ToTable("WORKFLOW", (string)null);
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Assignment", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Task", "IdtaskNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("Idtask")
                        .IsRequired()
                        .HasConstraintName("FK__ASSIGNMEN__IDTas__656C112C");

                    b.HasOne("Task_Manager_Beta.Data.User", "IduserNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("Iduser")
                        .IsRequired()
                        .HasConstraintName("FK__ASSIGNMEN__IDUse__6477ECF3");

                    b.Navigation("IdtaskNavigation");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Condition", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Permisssion", "IdpermissionNavigation")
                        .WithMany("Conditions")
                        .HasForeignKey("Idpermission")
                        .IsRequired()
                        .HasConstraintName("FK__CONDITION__IDPer__693CA210");

                    b.HasOne("Task_Manager_Beta.Data.Workflow", "IdworkflowNavigation")
                        .WithMany("Conditions")
                        .HasForeignKey("Idworkflow")
                        .IsRequired()
                        .HasConstraintName("FK__CONDITION__IDWor__6A30C649");

                    b.Navigation("IdpermissionNavigation");

                    b.Navigation("IdworkflowNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Listtemplate", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Template", "IdtemplateNavigation")
                        .WithMany("Listtemplates")
                        .HasForeignKey("Idtemplate")
                        .IsRequired()
                        .HasConstraintName("FK__LISTTEMPL__IDTem__6B24EA82");

                    b.Navigation("IdtemplateNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Member", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Project", "IdprojectNavigation")
                        .WithMany("Members")
                        .HasForeignKey("Idproject")
                        .IsRequired()
                        .HasConstraintName("FK__MEMBER__IDProjec__6383C8BA");

                    b.HasOne("Task_Manager_Beta.Data.User", "IduserNavigation")
                        .WithMany("Members")
                        .HasForeignKey("Iduser")
                        .IsRequired()
                        .HasConstraintName("FK__MEMBER__IDUser__628FA481");

                    b.Navigation("IdprojectNavigation");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Permisssion", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Project", "IdprojectNavigation")
                        .WithMany("Permisssions")
                        .HasForeignKey("Idproject")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISSSI__IDPro__6754599E");

                    b.HasOne("Task_Manager_Beta.Data.User", "IduserNavigation")
                        .WithMany("Permisssions")
                        .HasForeignKey("Iduser")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISSSI__IDUse__66603565");

                    b.Navigation("IdprojectNavigation");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Status", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Project", "IdprojectNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("Idproject")
                        .IsRequired()
                        .HasConstraintName("FK__STATUS__IDProjec__6C190EBB");

                    b.Navigation("IdprojectNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Task", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Project", "IdprojectNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Idproject")
                        .IsRequired()
                        .HasConstraintName("FK__TASK__IDProject__5FB337D6");

                    b.HasOne("Task_Manager_Beta.Data.Status", "IdstatusNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Idstatus")
                        .IsRequired()
                        .HasConstraintName("FK__TASK__IDStatus__60A75C0F");

                    b.Navigation("IdprojectNavigation");

                    b.Navigation("IdstatusNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Taskdetail", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Task", "IdtaskNavigation")
                        .WithOne("Taskdetail")
                        .HasForeignKey("Task_Manager_Beta.Data.Taskdetail", "Idtask")
                        .IsRequired()
                        .HasConstraintName("FK__TASKDETAI__IDTas__619B8048");

                    b.Navigation("IdtaskNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Workflow", b =>
                {
                    b.HasOne("Task_Manager_Beta.Data.Status", "IdstatusNavigation")
                        .WithMany("Workflows")
                        .HasForeignKey("Idstatus")
                        .IsRequired()
                        .HasConstraintName("FK__WORKFLOW__IDStat__68487DD7");

                    b.Navigation("IdstatusNavigation");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Permisssion", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Permisssions");

                    b.Navigation("Statuses");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Status", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Task", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Taskdetail");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Template", b =>
                {
                    b.Navigation("Listtemplates");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Members");

                    b.Navigation("Permisssions");
                });

            modelBuilder.Entity("Task_Manager_Beta.Data.Workflow", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
